version: '3.5'  

services:
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes: 
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    db:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./database:/database
      environment: 
        - POSTGRES_PASSWORD=password
        - DB_USERNAME=example
        - DB_PASSWORD=example
        - DB_NAME=example
        - DB_HOST=db
        - PGDATA=/database
    redis:
      image: redis
    frontend-excercise: 
      image: node-test
      ports: 
        - 5000:5000
    backend-excercise:
      image: back-test
      ports:
        - 8000:8000
      environment: 
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_NAME=postgres
        - DB_HOST=db
        - FRONT_URL=http://localhost
  
 